### ISSUE TITLE
[Feature Request] Double tap post to reply

### ISSUE THREAD

**Issue by floppyD** [K1rakishou/Kuroba#10]

**Comment by happapa** [comment]
Sounds unneccessary. There is already the "tap post number to reply" option.

**Comment by floppyD** [comment]
Which is not easy to tap on since it's small as fuck. And I'm asking for an extra option, leave to K1rakishou judge if it's unnecessary or not.

**Comment by Astridchan** [comment]
Double tap is already used for the "jump to reply" feature, so it might be confusing if double tap did one function on posts, and another thing on post replies. 

How about a "swipe left on post to reply" feature? Since a swipe from right to left currently has no action.

**Comment by floppyD** [comment]
I don't think it would be confusing, just leave a note saying that it doesn't work on post replies and/or associate another behavior to the post replies screen, like tapping and holding, that currently does nothing. Just swiping would be weird with no "card-like" feedback.

**Comment by happapa** [comment]
I would like to add that this doesn't sound like a very intuitive feature. I have not seen any other app use double tap this way.

**Comment by floppyD** [comment]
I have never seen an app do half the stuff Clover does but here we are. It doesn't matter if you think it's intuitive or not, it'll will not be enabled by default and there will be a quick explanation telling what it does, if the maintainer ever decides to implement it.
