### ISSUE TITLE
Revert scrollbar to the one on 4.4.3

### ISSUE THREAD

**Issue by floppyD** [K1rakishou/Kuroba#11]
Dunno what cheese was thinking

**Comment by happapa** [comment]
What do you mean? The scrollbar in 4.4.3 was more broken, it didn't even scroll all the way to the bottom.

**Comment by floppyD** [comment]
Well, it worked here. And wasn't this giant mess that can't be used to scroll, that disappears randomly and just has random behavior overall.

**Comment by happapa** [comment]
In that case, it should be at least be reverted to the 4.4.2 version.

**Comment by happapa** [comment]
Or 4.4.1, or whatever was the version that was the last one before the scrollbar disappeared.
