### ISSUE TITLE
[Feature Request] Throw error when trying to upload unsupported media type

### ISSUE THREAD

**Issue by maluhia** [K1rakishou/Kuroba#16]
Scan the extension of a file or MIME type when selected by the image file picker, to ensure it conforms with 4chan before it has uploaded and captcha filled out and submitted.

e.g. no uploading PDF, or image files over 4MB on certain boards, VP9, etc.

Keep in mind that some file upload rules are board-specific.

**Comment by namazso** [comment]
I don't think the boards disclose in any way what type / size limitations they have, so I'd say this is probably out of scope for a generic imageboard browsing app.
