### ISSUE TITLE
Clover 3.0.2 loads webms much faster than Kuroba 4.4.4

### ISSUE THREAD

**Issue by Pentaphon** [K1rakishou/Kuroba#4]
The issue happens when going on a webm-heavy thread like on /wsg/ or /gif/. When you flick through webms and play them one by one in a speedy fashion, they start to get slow to the point where the progress meter is barely crawling across the screen. They take minutes to load, even over Wifi on a decent device like a Moto G4. Meanwhile, Clover 3.0.2 does not do this when I flick through the same thread, on the same device, right after experiencing the slowness on Kuroba. Clover 3.0.2 just loads the webms almost instantaneously no matter how fast you flick through them, while Kuroba 4.4.4 will be stuck loading a webm for a minute or two, and do the same thing on the next webm.

**Comment by happapa** [comment]
Can confirm.  Version 3.0.3 (last one on F-Droid) also loads fast.

**Comment by Pentaphon** [comment]
@happapa Unrelated but I don't see 3.0.3 on F-Droid. 

https://f-droid.org/en/packages/org.floens.chan/

**Comment by happapa** [comment]
You're right, F-Droid just showed that 3.0.3 was the latest version I had installed. Nevertheless, it still worked fine there.
