### ISSUE TITLE
Does anyone actaully use "Push thread to another device via NFC"?

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba#6]
Maybe it should just be deleted? Because NFC permission is kinda dangerous. It is only being used for this questionable feature.

**Comment by Astridchan** [comment]
I agree that it should go, it is unnecessary since there's numerous other ways to share threads between phones.

**Comment by Pentaphon** [comment]
Remove anything that is non-essential to Kuroba, please. Nobody uses it.

**Comment by lovepupils** [comment]
I vote in favor of removing it.

**Comment by Kattus** [comment]
off with its head I say!
