### ISSUE TITLE
[Bug] Revert changes in gallery mode

### ISSUE THREAD

**Issue by happapa** [K1rakishou/Kuroba#7]
Dickcheese fucked up the gallery in version 4.4.3 and it wasn't fixed in 4.4.4. When a thread with many images is opened and the gallery mode is started, thumbnails load at a snail pace and zooming into one can't be done until all thumbnails have been loaded. Version 4.4.2 with low res thumbnails worked perfectly.

**Comment by floppyD** [comment]
I think 4chan native thumbnails should be used unless prefetching is enabled. And maybe you should try to apply gallery like thumbnails to everything else when prefetching is enabled? Like, load low-res thumbnails, then start downloading content and slowly replacing them.
